<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>DrillFlow.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="PresentationCore" />
    <Reference Include="System.Net.Http" />
    <Reference Include="WindowsBase" />
    <ProjectReference Include="..\..\src\DrillFlow.Core\DrillFlow.Core.csproj" />
    <ProjectReference Include="..\..\src\DrillFlow.Application\DrillFlow.Application.csproj" />
    <ProjectReference Include="..\..\src\DrillFlow.Infrastructure\DrillFlow.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\DrillFlow.Desktop\DrillFlow.Desktop.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
